# .github/workflows/auto-assign.yml
name: Auto assign reviewers

on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, synchronize, edited]

permissions:
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: .github/auto_assign.yml
