name: Gemini PR Review (slash)

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:
  run-if-command:
    if: |
      github.event.issue.pull_request != null &&
      contains(github.event.comment.body, '/gemini review')
    uses: ./.github/workflows/gemini-pr-review.yml
    with:
      full_context: true
    secrets: inherit
